# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app/dashboard

# Copy package.json and package-lock.json
COPY dashboard/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY dashboard .

# Build the Next.js application
RUN npm run build

# Expose port 3000 for the Next.js application
EXPOSE 3000

# Run the Next.js application
CMD ["npm", "start"]